<?php
session_start();
include('db.php');
require('fpdf.php');

// Ensure user is logged in
if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}

if (isset($_POST['submit_requisition'])) {

    $user_id = $_SESSION['user_id'];

    // Fetch user + group details
    $query = "SELECT u.first_name, u.last_name, u.role, u.group_id, 
                     g.group_name, g.group_logo 
              FROM users u
              JOIN groups g ON u.group_id = g.id
              WHERE u.id = ?";
              
    $stmt = $conn->prepare($query);
    $stmt->bind_param('i', $user_id);
    $stmt->execute();
    $stmt->bind_result($first_name, $last_name, $role, $group_id, $group_name, $group_logo);
    $stmt->fetch();
    $stmt->close();

    if (!$group_id) {
        die("User group not found.");
    }

    $full_name = $first_name . ' ' . $last_name;

    // Validate requisition items
    if (!isset($_SESSION['requisition_items']) || !is_array($_SESSION['requisition_items']) || empty($_SESSION['requisition_items'])) {
        die("Requisition items are missing.");
    }

    $items = $_SESSION['requisition_items'];
    $total_amount = 0;

    foreach ($items as $item) {
        $total_amount += $item['total_cost'];
    }

    // ---------------- PDF GENERATION ----------------
    $pdf = new FPDF();
    $pdf->AddPage();

    // Church Logo (left side - static)
    if (file_exists('assets/img/log2.png')) {
        $pdf->Image('assets/img/log2.png', 10, 6, 30);
    }

    // Group Logo (right side - from DB)
   if (!empty($group_logo)) {

    // Create unique temporary file
    $temp_file = tempnam(sys_get_temp_dir(), 'logo_');

    file_put_contents($temp_file, $group_logo);

    // Detect image type
    $image_info = getimagesize($temp_file);

    if ($image_info === false) {
        unlink($temp_file);
        die("Invalid logo image.");
    }

    $mime = $image_info['mime'];

    switch ($mime) {
        case 'image/jpeg':
            $new_file = $temp_file . '.jpg';
            break;
        case 'image/png':
            $new_file = $temp_file . '.png';
            break;
        case 'image/gif':
            $new_file = $temp_file . '.gif';
            break;
        default:
            unlink($temp_file);
            die("Unsupported logo format.");
    }

    rename($temp_file, $new_file);

    // Add image to PDF
    $pdf->Image($new_file, 170, 6, 25);

    // Delete temp file
    unlink($new_file);
}

    // Church Info
    $pdf->SetFont('Arial', 'B', 14);
    $pdf->SetTextColor(0, 0, 128);
    $pdf->Cell(0, 10, 'PRESBYTERIAN CHURCH OF EAST AFRICA', 0, 1, 'C');
    $pdf->Cell(0, 8, 'MUKINYI CHURCH', 0, 1, 'C');

    $pdf->SetFont('Arial', '', 11);
    $pdf->Cell(0, 6, 'P.O BOX 60081-00200, Nairobi, Kenya', 0, 1, 'C');
    $pdf->Cell(0, 6, 'Tel: 0720 510 840 | Email: pceamukinyi@gmail.com', 0, 1, 'C');

    $pdf->Ln(10);

    // Requisition Header
    $pdf->SetFillColor(230, 230, 250);
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->SetTextColor(0);
    $pdf->Cell(0, 10, "REQUISITION DETAILS", 0, 1, 'C', true);

    $pdf->Ln(5);

    $pdf->SetFont('Arial', '', 11);
    $pdf->Cell(0, 8, "Group: $group_name", 0, 1);
    $pdf->Cell(0, 8, "Created by: $full_name ($role)", 0, 1);
    $pdf->Cell(0, 8, "Date: " . date('Y-m-d H:i:s'), 0, 1);

    $pdf->Ln(10);

    // Table Header
    $pdf->SetFont('Arial', 'B', 11);
    $pdf->SetFillColor(100, 149, 237);
    $pdf->SetTextColor(255, 255, 255);

    $pdf->Cell(10, 8, '#', 1, 0, 'C', true);
    $pdf->Cell(60, 8, 'Item Name', 1, 0, 'C', true);
    $pdf->Cell(30, 8, 'Cost', 1, 0, 'C', true);
    $pdf->Cell(25, 8, 'Qty', 1, 0, 'C', true);
    $pdf->Cell(35, 8, 'Total', 1, 1, 'C', true);

    // Table Data
    $pdf->SetFont('Arial', '', 10);
    $pdf->SetTextColor(0);

    $counter = 1;
    foreach ($items as $item) {

        $pdf->Cell(10, 8, $counter++, 1);
        $pdf->Cell(60, 8, $item['item_name'], 1);
        $pdf->Cell(30, 8, number_format($item['item_cost'], 2), 1);
        $pdf->Cell(25, 8, $item['item_quantity'], 1);
        $pdf->Cell(35, 8, number_format($item['total_cost'], 2), 1);
        $pdf->Ln();
    }

    // Total
    $pdf->Ln(5);
    $pdf->SetFont('Arial', 'B', 11);
    $pdf->SetFillColor(173, 216, 230);

    $pdf->Cell(125, 8, 'TOTAL AMOUNT', 1);
    $pdf->Cell(35, 8, number_format($total_amount, 2), 1, 1);

    // Footer
    $pdf->Ln(15);
    $pdf->SetFont('Arial', 'I', 9);
    $pdf->Cell(0, 8, 'Generated by Requisition Management System', 0, 0, 'C');

    // Capture PDF as string
    $pdf_content = $pdf->Output('', 'S');

    // Save into database
    $stmt = $conn->prepare("INSERT INTO requisitions 
        (group_id, created_by, total_amount, requisition_pdf, status, created_at) 
        VALUES (?, ?, ?, ?, 'Pending', NOW())");

    $stmt->bind_param('iids', $group_id, $user_id, $total_amount, $pdf_content);
    $stmt->execute();
    $stmt->close();

    // Clear session items after saving
    unset($_SESSION['requisition_items']);

    header("Location: main_dashboard.php?message=Requisition saved successfully");
    exit();
}
?>